Repository Kwon-TaeYun/momentree_blog, pull requests merged in 2025-04, with the labels that each got.

#20 feat: develop에 user 엔티티 추가(#12)
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
Labels: feature

#30 [feat#17] Follow, Blog 엔티티 설계
  .github/workflows/gemini-code-review.yml
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/entity/Blog.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/follower/entity/Follower.java
Labels: feature

#42 feat: feature#32 잠시 결합
  backend/db_dev.mv.db
  backend/momentreeblog/.gitignore
  backend/momentreeblog/build.gradle.kts
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/MomentreeblogApplication.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SwaggerConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/CustomAuthenticationFilter.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/dto/CustomUserDetails.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/exception/CustomAuthenticationEntryPoint.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/exception/JwtExceptionCode.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/token/JwtAuthenticationToken.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/repository/BlogRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/entity/Board.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/controller/RoleApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/entity/Role.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/repository/RoleRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/service/RoleService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserLoginDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserLoginResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserSignupDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/repository/UserRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/util/jwt/JwtTokenizer.java
  backend/momentreeblog/src/main/resources/application.yml
  backend/terraform-project/.gitignore
  backend/terraform-project/.terraform.lock.hcl
  backend/terraform-project/main.tf
  backend/terraform-project/terraform-project.iml
  backend/terraform-project/terraform.tfstate
  backend/terraform-project/terraform.tfstate.backup
  backend/terraform-project/variables.tf
  db_dev.mv.db
Labels: feature

#41 [feat] 블로그, 카테고리 CRUD
  backend/momentreeblog/.gitignore
  backend/momentreeblog/build.gradle.kts
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/controller/BlogController.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/dto/BlogCreateRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/dto/BlogRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/dto/BlogResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/dto/BlogUpdateRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/entity/Blog.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/repository/BlogRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/service/BlogService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/category/controller/CategoryController.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/category/dto/CategoryCreateRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/category/dto/CategoryResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/category/dto/CategoryUpdateRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/category/entity/Category.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/category/repository/CategoryRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/category/service/CategoryService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/repository/UserRepository.java
  backend/momentreeblog/src/main/resources/application.yml
  backend/momentreeblog/src/main/resources/data.sql
Labels: feature

#45 feat: feature/#32 develop에 병합
  .gitignore
  backend/db_dev.mv.db
  backend/db_dev.trace.db
  backend/momentreeblog/.gitignore
  backend/momentreeblog/build.gradle.kts
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/MomentreeblogApplication.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SwaggerConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/CustomAuthenticationFilter.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/dto/CustomUserDetails.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/exception/CustomAuthenticationEntryPoint.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/exception/JwtExceptionCode.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/token/JwtAuthenticationToken.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/repository/BlogRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardListResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/entity/Board.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/repository/BoardRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/comment/dto/CommentDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/comment/dto/CommentRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/comment/entity/Comment.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/comment/repository/CommentRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/comment/service/CommentService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/like/dto/BoardLikeInfoDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/like/entity/Like.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/like/repository/LikeRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/like/service/LikeService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/controller/RoleApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/entity/Role.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/repository/RoleRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/service/RoleService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserLikeDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserLoginDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserLoginResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserSignupDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/repository/UserRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/util/jwt/JwtTokenizer.java
  backend/momentreeblog/src/main/resources/application.yml
  backend/terraform-project/.gitignore
  backend/terraform-project/.terraform.lock.hcl
  backend/terraform-project/main.tf
  backend/terraform-project/terraform-project.iml
  backend/terraform-project/terraform.tfstate
  backend/terraform-project/terraform.tfstate.backup
  backend/terraform-project/variables.tf
  db_dev.mv.db
Labels: fix

#61 [feat/#56] 프론트엔드 로그인 페이지 기초 설계
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/jpa/BaseEntity.java
  frontend/package-lock.json
  frontend/package.json
  frontend/public/kakao_login.png
  frontend/public/logo.png
  frontend/src/app/login/page.tsx
Labels: feature

#77 [Feature/#75] 프론트엔드 "개인 블로그 페이지" 기초 설계
  frontend/next.config.js
  frontend/src/app/members/login/myblog/page.tsx
Labels: feature

#83 [feat/#68]: 프론트 게시글 사진 모아보기
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/BoardPhotoApiV1Controller.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/boards/[boardId]/photos/page.tsx
Labels: feature

#89 [feat/#71] 프론트 엔드 상세페이지 다시 구현
  frontend/src/app/boards/[boardId]/edit/page.tsx
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/[boardId]/photos/page.tsx
Labels: feature

#95 feat: 상단 페이지 통일 관련 기능 수정 및 추가
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/entity/Board.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/controller/RoleApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/controller/RoleInitializer.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/entity/Role.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/repository/RoleRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/role/service/RoleService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/rq/Rq.java
  backend/momentreeblog/src/main/resources/application.yml
  frontend/package-lock.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/members/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/prettierrc.json
  frontend/src/app/success/page.tsx
  frontend/src/store/auth/loginMember.tsx
  frontend/src/stores/auth/loginMember.tsx
Labels: feature, fix

#92 [Feature/#86] 회원정보찾기 - (이름+이메일) 추가
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserFindApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/repository/UserRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserFindService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserFindServiceImpl.java
Labels: feature

#91 [feat] 게시글 상세보기 기능 구현
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardDetailResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
Labels: feature

#102 feat: 회원탈퇴기능 구현(#90)
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/dto/CustomUserDetails.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/dto/BlogResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/service/BlogService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/entity/Board.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/FollowApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserDeleteRequest.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserFollowDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserSignupDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/repository/FollowRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/FollowService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/FollowServiceImpl.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/userenum/UserStatus.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/security/CustomAuthorizationRequestResolver.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/security/SecurityUser.java
Labels: feature

#101 [Feature/#98]사용자별 게시글 조회, 게시글 상세보기 기능 테스트 및 수정
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/repository/BoardRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
Labels: feature

#108 [feat/#105] 프론트엔드 게시물 생성 페이지 백엔드 연결 구현
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/controller/BlogApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/repository/BlogRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/service/BlogService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/entity/Board.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/category/entity/Category.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/category/repository/CategoryRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/BoardPhotoApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/entity/Photo.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/PhotoV1Service.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserDeleteRequest.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/rq/Rq.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/jwt/JwtTokenizer.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/security/CustomAuthorizationRequestResolver.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/boards/[boardId]/edit/page.tsx
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/[boardId]/photos/page.tsx
  frontend/src/app/boards/new/page.tsx
  frontend/src/app/boards/page.tsx
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/app/members/login/myblog/picture/page.tsx
  frontend/src/app/members/login/page.tsx
  frontend/src/app/success/page.tsx
  frontend/src/components/layout/Header.tsx
Labels: feature

#109 feat:게시글 목록, 좋아요, 게시글 상세보기 기능 구현
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardDetailResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/rq/Rq.java
Labels: feature

#111 feat: 좋아요 관련 기능 구현 완료
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardDetailResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardListResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/like/service/LikeService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/new/page.tsx
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/app/members/signup/page.tsx
  frontend/src/components/LikeList.tsx
  frontend/src/components/layout/Header.tsx
Labels: feature

#120 [feat/#117] 게시글 삭제 페이지 프론트엔드 구현 및 일부 수정
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/new/page.tsx
Labels: feature

#124 [Feature/#99] 프론트엔드 회원정보찾기 스크립트 작성
  backend/db_dev.mv.db
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/service/BlogService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/FollowApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserDeleteRequest.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/repository/FollowRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/FollowService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/FollowServiceImpl.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/rq/Rq.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/jwt/JwtTokenizer.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/security/CustomAuthorizationRequestResolver.java
  backend/momentreeblog/src/main/resources/application.yml
  backend/terraform-project/.gitignore
  backend/terraform-project/.terraform.lock.hcl
  backend/terraform-project/main.tf
  backend/terraform-project/terraform-project.iml
  backend/terraform-project/terraform.tfstate
  backend/terraform-project/terraform.tfstate.backup
  backend/terraform-project/variables.tf
  frontend/src/app/members/find/id/page.tsx
  frontend/src/app/members/find/page.tsx
  frontend/src/app/members/find/password/page.tsx
  frontend/src/app/members/login/page.tsx
  frontend/src/app/members/signup/page.tsx
  package-lock.json
Labels: feature

#125 [Feature/#100] 프론트엔드 팔로우 기능 스크립트 작성
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/components/user_follower.tsx
Labels: feature

#130 Feature/#127
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserFindApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserResponse.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/app/members/login/page.tsx
  frontend/src/app/members/signup/page.tsx
  frontend/src/app/mypage/account/page.tsx
  frontend/src/app/mypage/page.tsx
  frontend/src/app/mypage/withdraw/page.tsx
  frontend/src/stores/auth/loginMember.tsx
Labels: feature

#131 [Feature/#129] 프론트엔드 팔로우 기능 스크립트 수정2
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/security/CustomAuthenticationFilter.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/jwt/JwtTokenizer.java
  backend/momentreeblog/src/main/resources/application.yml
  backend/momentreeblog/src/main/resources/data.sql
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/app/members/signup/page.tsx
  frontend/src/components/user_follower.tsx
Labels: fix

#119 [feat/#113] 프론트엔드 게시글 수정 페이지, 게시글 생성 페이지 구현 사진 구현 완료
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/controller/BlogApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardDetailResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardEditResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/entity/Board.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/BoardPhotoApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/entity/Photo.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/PhotoV1Service.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserDeleteRequest.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/global/util/jwt/JwtTokenizer.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/boards/[boardId]/edit/page.tsx
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/[boardId]/photos/page.tsx
  frontend/src/app/boards/new/page.tsx
  frontend/src/app/boards/page.tsx
  frontend/src/app/home/page.tsx
  frontend/src/app/members/login/myblog/picture/page.tsx
  frontend/src/app/members/login/page.tsx
  frontend/src/components/layout/Header.tsx
Labels: feature

#133 feat:카테고리 관련 기능 구현 완료
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/repository/BoardRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/category/controller/CategoryController.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/category/repository/CategoryRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/category/service/CategoryService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserDto.java
  frontend/src/app/boards/new/page.tsx
  frontend/src/stores/auth/loginMember.tsx
Labels: feature

#135 [feat] 프론트엔드 게시글에 댓글 CRUD 기능 구현
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/comment/dto/CommentDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/comment/service/CommentService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/userenum/UserStatus.java
  frontend/.idea/.gitignore
  frontend/.idea/frontend.iml
  frontend/.idea/misc.xml
  frontend/.idea/modules.xml
  frontend/.idea/vcs.xml
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/home/page.tsx
  frontend/src/app/members/signup/page.tsx
Labels: feature

#138 [Feat/#137] 블로그 상세보기 일부 구현
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/controller/BlogApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/dto/BlogDetailResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/service/BlogService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/repository/BoardRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  frontend/src/app/blog/[id]/page.tsx
  frontend/src/app/home/page.tsx
Labels: feature

#140 [fix] 회원 정보 수정 기능 내 카테고리 수정 기능 추가
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/entity/Photo.java
  frontend/src/app/boards/[boardId]/edit/page.tsx
Labels: fix

#136 [Refactor/#129] 프론트엔드 팔로워/팔로잉 기능 팝업 API 완료
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/FollowApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/repository/FollowRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/FollowServiceImpl.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserFindServiceImpl.java
  frontend/src/components/user_follower.tsx
Labels: fix

#142 [feat/#139] 프론트엔드 사진첩 구현 완료
  backend/momentreeblog/build.gradle.kts
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardDetailResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardEditResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardListResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardMyBlogResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/dto/BoardRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/entity/Board.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/BoardPhotoApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/ProfilePhotoApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/dto/board/PhotoAlbumDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/repository/PhotoRepository.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/PhotoV1Service.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/board/BoardPhotoService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/profile/ProfilePhotoService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/s3/controller/S3ApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/s3/dto/response/PreSignedUrlResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/s3/service/S3V1Service.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  backend/momentreeblog/src/main/resources/application.yml
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/boards/[boardId]/edit/page.tsx
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/[boardId]/photos/page.tsx
  frontend/src/app/boards/new/page.tsx
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/app/photoList/page.tsx
Labels: feature

#145 [feat/#112] 프론트엔드 홈 화면 구현 완료
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/BoardPhotoApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/dto/board/AdditionalPhotoSaveRequest.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/s3/service/S3V1Service.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserResponse.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  frontend/src/app/boards/[boardId]/edit/page.tsx
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/new/page.tsx
  frontend/src/app/home/page.tsx
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/toastui-i18n.d.ts
  frontend/src/types/toast-ui.d.ts
Labels: feature

#148 [Feature/#144] 홈 화면 및 블로그 상세보기 구현
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/dto/BlogDetailResponseDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/service/BlogService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserFindApiV1Controller.java
  frontend/src/app/blog/[id]/page.tsx
  frontend/src/app/home/page.tsx
Labels: feature

#149 [feat/fix/#146] 프로필 사진 수정 구현 완료 및 프론트 에러 수정
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/config/SecurityConfig.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/BoardPhotoApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/controller/ProfilePhotoApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/PhotoV1Service.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/board/BoardPhotoService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/photo/photo/service/profile/ProfilePhotoService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/s3/controller/S3ApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/s3/dto/request/PhotoUploadRequestDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/s3/service/S3V1Service.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserDto.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserResponse.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/service/UserService.java
  frontend/src/app/boards/[boardId]/edit/page.tsx
  frontend/src/app/boards/[boardId]/page.tsx
  frontend/src/app/boards/[boardId]/photos/page.tsx
  frontend/src/app/boards/new/page.tsx
  frontend/src/app/home/page.tsx
  frontend/src/app/members/login/myblog/page.tsx
  frontend/src/app/mypage/page.tsx
  frontend/src/toastui-i18n.d.ts
  frontend/src/types/toast-ui.d.ts
Labels: feature, fix

#150 [Feature/#143] 재PR - 팔로우 기능
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/controller/BlogApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/blog/blog/service/BlogService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/controller/BoardApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/board/service/BoardService.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/board/category/entity/Category.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/controller/UserApiV1Controller.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/dto/UserResponse.java
  backend/momentreeblog/src/main/java/com/likelion/momentreeblog/domain/user/user/entity/User.java
  frontend/public/default-content.jpg
  frontend/src/app/blog/[id]/page.tsx
  frontend/src/app/home/page.tsx
  frontend/src/app/members/login/page.tsx
  frontend/src/components/user_follower.tsx
Labels: duplicate
